//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardMonitor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class CMSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CMSettings defaultInstance = ((CMSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CMSettings())));
        
        public static CMSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Alex Castro\\Desktop\\Connect to Server.rdp")]
        public string RDPLocation {
            get {
                return ((string)(this["RDPLocation"]));
            }
            set {
                this["RDPLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LLFADB119")]
        public string Keyword {
            get {
                return ((string)(this["Keyword"]));
            }
            set {
                this["Keyword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InitialSetup {
            get {
                return ((bool)(this["InitialSetup"]));
            }
            set {
                this["InitialSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MLFADB119")]
        public string MailKeyword {
            get {
                return ((string)(this["MailKeyword"]));
            }
            set {
                this["MailKeyword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Alex Castro\\AppData\\Roaming\\Microsoft\\Templates\\Ticket Request.oft")]
        public string TemplateLocation {
            get {
                return ((string)(this["TemplateLocation"]));
            }
            set {
                this["TemplateLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$ID$")]
        public string IndexID {
            get {
                return ((string)(this["IndexID"]));
            }
            set {
                this["IndexID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$EM$")]
        public string IndexEM {
            get {
                return ((string)(this["IndexEM"]));
            }
            set {
                this["IndexEM"] = value;
            }
        }
    }
}
